// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9B53uijJPoUcBG9rrGH_v4STEZ90quXA',
    appId: '1:392508468357:android:92fd718c9305d275940dec',
    messagingSenderId: '392508468357',
    projectId: 'brick-collector-3d1bc',
    storageBucket: 'brick-collector-3d1bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnon2FwkWX45GajLOKc3wV7ChMLUYeN_E',
    appId: '1:392508468357:ios:64679c788dcffd59940dec',
    messagingSenderId: '392508468357',
    projectId: 'brick-collector-3d1bc',
    storageBucket: 'brick-collector-3d1bc.firebasestorage.app',
    iosBundleId: 'com.example.brickCollector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnon2FwkWX45GajLOKc3wV7ChMLUYeN_E',
    appId: '1:392508468357:ios:68ab5bdfe4f7e89a940dec',
    messagingSenderId: '392508468357',
    projectId: 'brick-collector-3d1bc',
    storageBucket: 'brick-collector-3d1bc.firebasestorage.app',
    iosBundleId: 'de.fpe.brickCollector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwSTEaSWgR1qX2Akb-waTvZ9-7FKcXwoM',
    appId: '1:392508468357:web:09acca0cf156d0cc940dec',
    messagingSenderId: '392508468357',
    projectId: 'brick-collector-3d1bc',
    authDomain: 'brick-collector-3d1bc.firebaseapp.com',
    storageBucket: 'brick-collector-3d1bc.firebasestorage.app',
  );
}